import { Professor } from "@/interfaces";

export const DUMMY_PROFESSORS: Professor[] = [
  {
    id: "1",
    nombres: "María Elena",
    apellidos: "González Pérez",
    cedula: "12345678",
    email: "maria.gonzalez@escuela.edu",
    telefono: "3001234567",
    cargo: "Docente Titular",
    estado: "activa",
    nivelEducativo: "basica_primaria",
    materias: ["Matemáticas", "Ciencias Naturales"],
    materiasAsignadas: ["Matemáticas 3°", "Ciencias 3°"],
    institucionGraduacion: "Universidad Pedagógica Nacional",
    fechaVinculacion: "2020-02-15",
    fechaNacimiento: "1985-06-20",
    direccion: "Calle 123 #45-67, Bogotá",
    experienciaAnios: 8,
    observaciones: "Excelente desempeño académico",
  },
  {
    id: "2",
    nombres: "Carlos Alberto",
    apellidos: "Rodríguez Silva",
    cedula: "87654321",
    email: "carlos.rodriguez@escuela.edu",
    telefono: "3009876543",
    cargo: "Coordinador Académico",
    estado: "activa",
    nivelEducativo: "basica_secundaria",
    materias: ["Física", "Química", "Matemáticas"],
    materiasAsignadas: ["Física 10°", "Química 11°"],
    institucionGraduacion: "Universidad Nacional de Colombia",
    fechaVinculacion: "2018-08-01",
    fechaNacimiento: "1980-03-15",
    direccion: "Carrera 50 #30-20, Medellín",
    experienciaAnios: 12,
    observaciones: "Líder en proyectos de innovación educativa",
  },
  // Nuevos profesores agregados
  {
    id: "3",
    nombres: "Sandra",
    apellidos: "Tovar",
    cedula: "11223344",
    email: "sandra.tovar@escuela.edu",
    telefono: "3001122334",
    cargo: "Docente Titular",
    estado: "activa",
    nivelEducativo: "basica_primaria",
    materias: ["Lenguaje", "Sociales"],
    materiasAsignadas: ["Lenguaje 4°", "Sociales 4°"],
    institucionGraduacion: "Universidad de Antioquia",
    fechaVinculacion: "2019-03-10",
    fechaNacimiento: "1988-11-05",
    direccion: "Calle 80 #45-30, Medellín",
    experienciaAnios: 7,
    observaciones: "Especialista en pedagogía infantil",
  },
  {
    id: "4",
    nombres: "Diana",
    apellidos: "Álvarez",
    cedula: "22334455",
    email: "diana.alvarez@escuela.edu",
    telefono: "3002233445",
    cargo: "Docente de Reemplazo",
    estado: "activa",
    nivelEducativo: "basica_primaria",
    materias: ["Matemáticas", "Ciencias"],
    materiasAsignadas: ["Matemáticas 3°", "Ciencias 3°"],
    institucionGraduacion: "Universidad de Medellín",
    fechaVinculacion: "2022-01-15",
    fechaNacimiento: "1992-04-18",
    direccion: "Carrera 65 #12-34, Medellín",
    experienciaAnios: 3,
    observaciones: "Nueva docente",
  },
  {
    id: "5",
    nombres: "Luis",
    apellidos: "Moreno",
    cedula: "33445566",
    email: "luis.moreno@escuela.edu",
    telefono: "3003344556",
    cargo: "Docente Titular",
    estado: "activa",
    nivelEducativo: "media",
    materias: ["Física", "Matemáticas"],
    materiasAsignadas: ["Física 10°", "Matemáticas 10°"],
    institucionGraduacion: "Universidad EAFIT",
    fechaVinculacion: "2017-09-20",
    fechaNacimiento: "1983-07-22",
    direccion: "Calle 50 #23-45, Medellín",
    experienciaAnios: 10,
    observaciones: "Coordinador de ciencias",
  },
  {
    id: "6",
    nombres: "Camilo",
    apellidos: "Pérez",
    cedula: "44556677",
    email: "camilo.perez@escuela.edu",
    telefono: "3004455667",
    cargo: "Docente de Reemplazo",
    estado: "activa",
    nivelEducativo: "media",
    materias: ["Química", "Biología"],
    materiasAsignadas: ["Química 11°", "Biología 11°"],
    institucionGraduacion: "Universidad CES",
    fechaVinculacion: "2023-02-01",
    fechaNacimiento: "1990-12-30",
    direccion: "Carrera 80 #45-67, Medellín",
    experienciaAnios: 4,
    observaciones: "Especialista en laboratorios",
  },
];