import { Professor } from "@/interfaces/intex";

export const DUMMY_PROFESSORS: Professor[] = [
  {
    id: "1",
    nombres: "María Elena",
    apellidos: "González Pérez",
    cedula: "12345678",
    email: "maria.gonzalez@escuela.edu",
    telefono: "3001234567",
    cargo: "Docente Titular",
    estado: "activa",
    nivelEducativo: "basica_primaria",
    materias: ["Matemáticas", "Ciencias Naturales"],
    materiasAsignadas: ["Matemáticas 3°", "Ciencias 3°"],
    institucionGraduacion: "Universidad Pedagógica Nacional",
    fechaVinculacion: "2020-02-15",
    fechaNacimiento: "1985-06-20",
    direccion: "Calle 123 #45-67, Bogotá",
    experienciaAnios: 8,
    observaciones: "Excelente desempeño académico",
  },
  {
    id: "2",
    nombres: "Carlos Alberto",
    apellidos: "Rodríguez Silva",
    cedula: "87654321",
    email: "carlos.rodriguez@escuela.edu",
    telefono: "3009876543",
    cargo: "Coordinador Académico",
    estado: "activa",
    nivelEducativo: "basica_secundaria",
    materias: ["Física", "Química", "Matemáticas"],
    materiasAsignadas: ["Física 10°", "Química 11°"],
    institucionGraduacion: "Universidad Nacional de Colombia",
    fechaVinculacion: "2018-08-01",
    fechaNacimiento: "1980-03-15",
    direccion: "Carrera 50 #30-20, Medellín",
    experienciaAnios: 12,
    observaciones: "Líder en proyectos de innovación educativa",
  },
]
