export * from './dummyUsers'
export * from './dummyGradeAndAssigment'
export * from './dummyDocuments'
export * from './dummyInstitutions'
export * from './dummyProfessors'
export * from './dummyStudents'
export * from './dummyDashboard'
export * from './dummySolicitudes'
export * from './dummyConductores'
export * from './dummyRutas'
export * from './dummyVehiculos'
export * from "./dummyRectores"
export * from "./dummyPae"
export * from "./dummyRectorDocuments.ts"
export * from "./dummySuplencias"
