
import { Suplencia } from "@/interfaces/suplencia";

export const DUMMY_SUPLENCIAS: Suplencia[] = [
  {
    id: "1",
    docenteAusenteId: "3",
    tipoAusencia: "Incapacidad EPS",
    fechaInicioAusencia: "2024-06-10",
    fechaFinAusencia: "2024-06-14",
    institucionId: "1",
    docenteReemplazoId: "4",
    fechaInicioReemplazo: "2024-06-11",
    fechaFinReemplazo: "2024-06-14",
    horasCubiertas: 12,
    jornada: "Única",
    concepto: "Reemplazo por Incapacidad",
    soporteIncapacidad: null,
    soporteHoras: null,
    observaciones: "Reemplazo completo de jornada",
  },
  {
    id: "2",
    docenteAusenteId: "5",
    tipoAusencia: "Licencia sin sueldo",
    fechaInicioAusencia: "2024-06-01",
    fechaFinAusencia: "2024-06-10",
    institucionId: "2",
    docenteReemplazoId: "6",
    fechaInicioReemplazo: "2024-06-03",
    fechaFinReemplazo: "2024-06-10",
    horasCubiertas: 18,
    jornada: "Nocturna",
    concepto: "Clases en jornada nocturna",
    soporteIncapacidad: null,
    soporteHoras: null,
    observaciones: "Licencia por trámites personales",
  },
  {
    id: "3",
    docenteAusenteId: "1",
    tipoAusencia: "Comisión oficial",
    fechaInicioAusencia: "2024-06-05",
    fechaFinAusencia: "2024-06-07",
    institucionId: "3",
    docenteReemplazoId: "2",
    fechaInicioReemplazo: "2024-06-06",
    fechaFinReemplazo: "2024-06-07",
    horasCubiertas: 6,
    jornada: "Sabatina",
    concepto: "Jornada especial",
    soporteIncapacidad: null,
    soporteHoras: null,
    observaciones: "Comisión del ministerio de educación",
  },
];
